apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-new-2022-prod
namePrefix: prod-
patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
  - service.yaml
resources:
  - ../../../base/be
images:
  - name: harbor.k8s.scg.skku.ac.kr/library/scg-new-2022-be
    newTag: prod1
